-- UI Dashboard：节点展示字段、配置版本备注、待下发版本

ALTER TABLE node ADD COLUMN IF NOT EXISTS region VARCHAR(64);
ALTER TABLE node ADD COLUMN IF NOT EXISTS remark TEXT;
ALTER TABLE node ADD COLUMN IF NOT EXISTS agent_os VARCHAR(32);
ALTER TABLE node ADD COLUMN IF NOT EXISTS agent_arch VARCHAR(32);
ALTER TABLE node ADD COLUMN IF NOT EXISTS virtualization VARCHAR(64);
ALTER TABLE node ADD COLUMN IF NOT EXISTS pending_deploy_version_id BIGINT REFERENCES config_version(id);

ALTER TABLE config_version ADD COLUMN IF NOT EXISTS display_name VARCHAR(256);
ALTER TABLE config_version ADD COLUMN IF NOT EXISTS remark TEXT;
